{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/9401af5/test-utils-9401af5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "9401af5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-jvm-9401af5.jar",
          "url": "test-utils-jvm-9401af5.jar",
          "size": 8814,
          "sha512": "781d2b0e7f57326902eb42a2cb6ac1543b2d6579f02d5a7e1ca7494fc0637855bf2a7d3eeb7f81e4c17d308ef15caaf51ac12bfdb0f4d8288718a3eba794eb12",
          "sha256": "44bf301136f31cf6d1ca73d46836792bfa091af066aeb6adee29deb7b3f5c570",
          "sha1": "33ed613d4d22ef8131fd93cc0e97951486a41006",
          "md5": "41bdfbc6fca4006dd92917b4d9cafcbb"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-jvm-9401af5.jar",
          "url": "test-utils-jvm-9401af5.jar",
          "size": 8814,
          "sha512": "781d2b0e7f57326902eb42a2cb6ac1543b2d6579f02d5a7e1ca7494fc0637855bf2a7d3eeb7f81e4c17d308ef15caaf51ac12bfdb0f4d8288718a3eba794eb12",
          "sha256": "44bf301136f31cf6d1ca73d46836792bfa091af066aeb6adee29deb7b3f5c570",
          "sha1": "33ed613d4d22ef8131fd93cc0e97951486a41006",
          "md5": "41bdfbc6fca4006dd92917b4d9cafcbb"
        }
      ]
    }
  ]
}
