{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/61a6ee5/test-utils-annotations-61a6ee5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "61a6ee5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations.klib",
          "url": "test-utils-annotations-iosarm64-61a6ee5.klib",
          "size": 11330,
          "sha512": "95edaa9d5a45aa325e6c8d9d925116e4078fbe4467e6fa87336bea4e882465c3f02ffb719870b456defbc2aa703b2be263250c11982c07c2b6c25a7ad49a8e4e",
          "sha256": "aaba8f8ce2a805b586621a9a295d37dea4d21292609dd8054ae66bf9542e356f",
          "sha1": "a5324c8f926b3f73bc066d0e3d0dbe27836b4ec0",
          "md5": "a05e6c182ac102851796dbfb2fe08f46"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-iosarm64-61a6ee5-metadata.jar",
          "url": "test-utils-annotations-iosarm64-61a6ee5-metadata.jar",
          "size": 261,
          "sha512": "5e0fb4f02d1748320860cb4023a4acc3bd8efd7c0445fa2db1666638c68fcc0e85d5c127ee05530049bae9e75579088ed12174093b9868fee9ae70ef772b98f5",
          "sha256": "234fb905bfe8faf67b0c6e9d52a13dd7d49414992a62ce7263bbe54fcf0b3465",
          "sha1": "582c3bb353bc7d6f9a8d30a5e8bcc9a8456cbc50",
          "md5": "7ea944254c125f087837b2cf12a84b8f"
        }
      ]
    }
  ]
}
