{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/9401af5/test-utils-ktor-9401af5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "9401af5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor.klib",
          "url": "test-utils-ktor-iosx64-9401af5.klib",
          "size": 15009,
          "sha512": "4e93ca692b3d72fbf9a4fdbd794f94a5ec38e33d445f7b94e637b151886b8730c15640e54b415bdfcaec9e1fae201c62d3ed351921ab0b4f73345ca84dc3fe40",
          "sha256": "41f9a94cd7e9c2fcf9efb9701afb93e9a22e5a8a0a0a98efd58d4a6574e3e65b",
          "sha1": "26b1deaf53980bf22abda88f41ca1c851780377d",
          "md5": "32ddceaa1e4e3f1feafdac0a398985f1"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-iosx64-9401af5-metadata.jar",
          "url": "test-utils-ktor-iosx64-9401af5-metadata.jar",
          "size": 261,
          "sha512": "b956423eb0ef67d721b5cd896bbc6ee8d26ff3fe72df7fb42a89c6ca386ebdd4d9b641b4ad615113905a594ed06a0e5039a0b51c3dbec16036b09b526d0331bb",
          "sha256": "1b214a51a69b003b7670fcd8f9920a87bc23e214d17721cde8ed84fae5727684",
          "sha1": "7b8dbed79b36734cdb70edb13fe44cc623a95be3",
          "md5": "4b9d35cb81cdb2e73ca2a304a8fef843"
        }
      ]
    }
  ]
}
