{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.mkdocs",
    "module": "antibytes-mkdocs",
    "version": "0e82305",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "0e82305"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-0e82305.jar",
          "url": "antibytes-mkdocs-0e82305.jar",
          "size": 11930,
          "sha512": "a54ceaf18c5af93659289b9de4166d72f48663cb1224aeca354973404d89574ad0954799bc9783edaf3d60e1e289c239d1c79302e1fe0f60994e021b277e0caa",
          "sha256": "512fe1bcd06ccbf7d160180545fa959f3de6799fd7962cf7cef877276c4c4712",
          "sha1": "c406a0a81ce68795ce734a401f00ff3879f6d5f9",
          "md5": "defe94bbac41a7f2096ef524fc8931db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-use-python-plugin",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "ru.vyarus",
          "module": "gradle-mkdocs-plugin",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "0e82305"
          }
        },
        {
          "group": "tech.antibytes.gradle.versioning",
          "module": "antibytes-versioning",
          "version": {
            "requires": "0e82305"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-mkdocs-0e82305.jar",
          "url": "antibytes-mkdocs-0e82305.jar",
          "size": 11930,
          "sha512": "a54ceaf18c5af93659289b9de4166d72f48663cb1224aeca354973404d89574ad0954799bc9783edaf3d60e1e289c239d1c79302e1fe0f60994e021b277e0caa",
          "sha256": "512fe1bcd06ccbf7d160180545fa959f3de6799fd7962cf7cef877276c4c4712",
          "sha1": "c406a0a81ce68795ce734a401f00ff3879f6d5f9",
          "md5": "defe94bbac41a7f2096ef524fc8931db"
        }
      ]
    }
  ]
}
