{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/61a6ee5/test-utils-coroutine-61a6ee5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "61a6ee5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosarm64-61a6ee5.klib",
          "size": 10124,
          "sha512": "6f1b87cc5fead1460cc7c8a6943d873389d65bf60ef4c8fa203ed21810a5dad4038da0eebe6bb9b90ef0b1f587e16e99f48370c593e54e6a788334303d03c885",
          "sha256": "aab199985bd5e67a4df1739aecc094ef2931f7bb304357fe28ff517f02a30c30",
          "sha1": "722a138aa6c815113b927e29b57762d968b2c11b",
          "md5": "b69ac5267b7d7b40a61ccdd92a821810"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosarm64-61a6ee5-metadata.jar",
          "url": "test-utils-coroutine-iosarm64-61a6ee5-metadata.jar",
          "size": 261,
          "sha512": "1d9b865565685b9e792dacbc1fd1744208413ed7082e8ef75413d682c8d9898a34bcff3941d314e322531d247a26f357207b5bc66a56eff89d95700050d66675",
          "sha256": "3496297f4f9249ff8edd88b88701ae5380413af41ed817cfc74492828cf69cd8",
          "sha1": "4806764c10f4e71e9195964095ede0716c8e7bf3",
          "md5": "29e6128d01d76c94a1c6de65a1c10c1d"
        }
      ]
    }
  ]
}
