{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-versioning",
    "version": "9e2ffe9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-versioning-9e2ffe9.jar",
          "url": "antibytes-versioning-9e2ffe9.jar",
          "size": 16029,
          "sha512": "1becbffa81923b8babc9a89fc6d67a74439ff2e60b1fe06238801e585b10e4059c05d4b64559b2db45d8029995330ce529695090366bbc2a9ebbc80fd0f18a6b",
          "sha256": "864bf23dbb9c59987a82c6ac944f7c0193c5c91ee28b01cb6570cf5eecf9f67b",
          "sha1": "9774e6be35679bb08c3023673863f31954b30cb9",
          "md5": "3e14a13cea009ebfbfb105a229404ab4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-versioning-9e2ffe9.jar",
          "url": "antibytes-versioning-9e2ffe9.jar",
          "size": 16029,
          "sha512": "1becbffa81923b8babc9a89fc6d67a74439ff2e60b1fe06238801e585b10e4059c05d4b64559b2db45d8029995330ce529695090366bbc2a9ebbc80fd0f18a6b",
          "sha256": "864bf23dbb9c59987a82c6ac944f7c0193c5c91ee28b01cb6570cf5eecf9f67b",
          "sha1": "9774e6be35679bb08c3023673863f31954b30cb9",
          "md5": "3e14a13cea009ebfbfb105a229404ab4"
        }
      ]
    }
  ]
}
