{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/61a6ee5/test-utils-61a6ee5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "61a6ee5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosarm64-61a6ee5.klib",
          "size": 7962,
          "sha512": "4a9c4a745a177b65290a8b6e1f4e45afc70018250e9ae064673b79e21097a78c70fdbb53a13b425478520c3b96d781a60435d7f3e70860d6cf3e70419e57b82c",
          "sha256": "c231e0f0fe7d17b3c8feebc5684c52f4f2e23e8c895ea9c6ab9bb1bafb5817ae",
          "sha1": "bd56568f4ff847bf496cb11403f05f4758bc54ac",
          "md5": "21bf8685971662cd968ba414c97652e7"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosarm64-61a6ee5-metadata.jar",
          "url": "test-utils-iosarm64-61a6ee5-metadata.jar",
          "size": 261,
          "sha512": "e7f647c378d3377827b2e99e1849d2b16628eb402b08fd4922450a94867152a12c1209e9ea46cab4f1876c8625d97460407905d55add6742872106e44dca6bdc",
          "sha256": "d691f43eb9fa2aec965ac736c5e2136a4750f0836a09841721ff50a01cf32be8",
          "sha1": "3163906fb2254cbe87230435672ec844eda7bc88",
          "md5": "966ddc3e63bc1e5f557d3e6dc1952a90"
        }
      ]
    }
  ]
}
