{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-grammar-tools",
    "version": "9e2ffe9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-9e2ffe9.jar",
          "url": "antibytes-grammar-tools-9e2ffe9.jar",
          "size": 39373,
          "sha512": "3f28009688565324fb41d36b7d6ed2bfda68a6aafd7c411419970dd496efe47b2bb63043056b7c49e375a9d09373f9ce71a6ef319411b16a173801ab1ec1c473",
          "sha256": "d060bb3366a3d91a4fb10dcda157a7e41ce074af15d7af41c6dfc1d58b16eab0",
          "sha1": "e5d09c04b3003a44bb3d7c694aae26cbe67057a8",
          "md5": "f22ea23541e4f3ebc00436e8f5ab7f99"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-9e2ffe9.jar",
          "url": "antibytes-grammar-tools-9e2ffe9.jar",
          "size": 39373,
          "sha512": "3f28009688565324fb41d36b7d6ed2bfda68a6aafd7c411419970dd496efe47b2bb63043056b7c49e375a9d09373f9ce71a6ef319411b16a173801ab1ec1c473",
          "sha256": "d060bb3366a3d91a4fb10dcda157a7e41ce074af15d7af41c6dfc1d58b16eab0",
          "sha1": "e5d09c04b3003a44bb3d7c694aae26cbe67057a8",
          "md5": "f22ea23541e4f3ebc00436e8f5ab7f99"
        }
      ]
    }
  ]
}
