{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/61a6ee5/test-utils-annotations-61a6ee5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "61a6ee5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-61a6ee5.klib",
          "url": "test-utils-annotations-js-61a6ee5.klib",
          "size": 9733,
          "sha512": "1f8d64b98498566ae2c79efc9cd86331694a011a72b78cc6197903d86191cba6677d782a4f20ff81dc2c885eed0d334617079cce59854a2b7b7b50dca8518c42",
          "sha256": "0e8bbe77adf32b227cabac34ff8f3e2be322feaaa354cbaa9e4e57890aa54743",
          "sha1": "87be57263ac6da3160b0ccb3d8528b3ddf997dac",
          "md5": "ad4927d74314933b6f8b5bb8a0db6661"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-61a6ee5.klib",
          "url": "test-utils-annotations-js-61a6ee5.klib",
          "size": 9733,
          "sha512": "1f8d64b98498566ae2c79efc9cd86331694a011a72b78cc6197903d86191cba6677d782a4f20ff81dc2c885eed0d334617079cce59854a2b7b7b50dca8518c42",
          "sha256": "0e8bbe77adf32b227cabac34ff8f3e2be322feaaa354cbaa9e4e57890aa54743",
          "sha1": "87be57263ac6da3160b0ccb3d8528b3ddf997dac",
          "md5": "ad4927d74314933b6f8b5bb8a0db6661"
        }
      ]
    }
  ]
}
