{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/9401af5/test-utils-coroutine-9401af5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "9401af5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosarm64-9401af5.klib",
          "size": 10124,
          "sha512": "6f1b87cc5fead1460cc7c8a6943d873389d65bf60ef4c8fa203ed21810a5dad4038da0eebe6bb9b90ef0b1f587e16e99f48370c593e54e6a788334303d03c885",
          "sha256": "aab199985bd5e67a4df1739aecc094ef2931f7bb304357fe28ff517f02a30c30",
          "sha1": "722a138aa6c815113b927e29b57762d968b2c11b",
          "md5": "b69ac5267b7d7b40a61ccdd92a821810"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosarm64-9401af5-metadata.jar",
          "url": "test-utils-coroutine-iosarm64-9401af5-metadata.jar",
          "size": 261,
          "sha512": "e64922344743d3873307b052d792e916d3cc7d58f8138621c5b3fb8df3f26932d963c73814044602c52c321f1f7363fd238503c605747a3ddb98ae1f973c54b7",
          "sha256": "0eb835f07e0aea608928bc3ef0a7df7aa40d9a48cbd14e4ef18444fed35016c8",
          "sha1": "ff03ff0956645ad7b042ffc03abed9f59ab2b071",
          "md5": "4fea52442d68d4f427f828be8f89a290"
        }
      ]
    }
  ]
}
