{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/9401af5/test-utils-9401af5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "9401af5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosx64-9401af5.klib",
          "size": 14299,
          "sha512": "0e804765cf59a9de4515bc61295a685b8f9fdd70190de83af5a2390ce33eff7206dcf8927bd286aef157b7069007ff9406f3a13e7f151543e23caf2ea4ac71b8",
          "sha256": "e9a41232638f5fb5d45085c9a5cc533abf3e5a88fca4f7cc348ee55b0a288aeb",
          "sha1": "c157282ae310c0c389477642217ea5fc2c08aefc",
          "md5": "d682f8ea504b651e47e2f2ea30a4f23a"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosx64-9401af5-metadata.jar",
          "url": "test-utils-iosx64-9401af5-metadata.jar",
          "size": 261,
          "sha512": "29192d8506440c317e15e4cba376f3649f431fbb95541c271c64473d9b0b316cbdaf579b3f6a600726e994496ecc7089a5ae73bfda9a6cf31b3d4e330f5d6985",
          "sha256": "0232f07caa62f56feb32b4432af6d5b7f610951f6ed4c185b099fcf8d3e7254b",
          "sha1": "7e8db6f5765b2765a323d9835790eefa7b86a4eb",
          "md5": "a3d94c8ec8a4eaa939de6756ac1f9359"
        }
      ]
    }
  ]
}
