{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/61a6ee5/test-utils-ktor-61a6ee5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "61a6ee5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-ktor-jvm-61a6ee5.jar",
          "url": "test-utils-ktor-jvm-61a6ee5.jar",
          "size": 26352,
          "sha512": "f590aae3ec7f61eef5a3b38ceb515cd45be55cbaec8ee0a6e894e513c6060307892cfa0a333720f2442a0e6a1e1f3da1b69048384ea8ed89d370b4011569c8c7",
          "sha256": "8d862484082b6f8629b04ec89ca8e6e1ac080cd561f3326008e0b284ffad17ff",
          "sha1": "e7d64907e9330462fdc31499b7b68c62155f3387",
          "md5": "2e91267b2b7eabeb990b7b8dc6bc3edf"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-java",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm-61a6ee5.jar",
          "url": "test-utils-ktor-jvm-61a6ee5.jar",
          "size": 26352,
          "sha512": "f590aae3ec7f61eef5a3b38ceb515cd45be55cbaec8ee0a6e894e513c6060307892cfa0a333720f2442a0e6a1e1f3da1b69048384ea8ed89d370b4011569c8c7",
          "sha256": "8d862484082b6f8629b04ec89ca8e6e1ac080cd561f3326008e0b284ffad17ff",
          "sha1": "e7d64907e9330462fdc31499b7b68c62155f3387",
          "md5": "2e91267b2b7eabeb990b7b8dc6bc3edf"
        }
      ]
    }
  ]
}
