{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/61a6ee5/test-utils-coroutine-61a6ee5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "61a6ee5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iosx64-61a6ee5.klib",
          "size": 10107,
          "sha512": "106e50c2ef08425a51366534db2fb184b8ac4ef80f087fff01f6c2bb9cd2d020f7cc88df0359720da4f6d13259325286574fe557c0285f1eacd22df07164453e",
          "sha256": "fa5c2d721e6cd6f1c9611f16760b87b2629af2a04419266852a2b68a97db350a",
          "sha1": "13e7453d88d68c5b8f25d07228ba0e1f8c6864cd",
          "md5": "c147117cb33e9beb33ed14f8ef84ead8"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iosx64-61a6ee5-metadata.jar",
          "url": "test-utils-coroutine-iosx64-61a6ee5-metadata.jar",
          "size": 261,
          "sha512": "1d9b865565685b9e792dacbc1fd1744208413ed7082e8ef75413d682c8d9898a34bcff3941d314e322531d247a26f357207b5bc66a56eff89d95700050d66675",
          "sha256": "3496297f4f9249ff8edd88b88701ae5380413af41ed817cfc74492828cf69cd8",
          "sha1": "4806764c10f4e71e9195964095ede0716c8e7bf3",
          "md5": "29e6128d01d76c94a1c6de65a1c10c1d"
        }
      ]
    }
  ]
}
