{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.dependency.helper",
    "module": "antibytes-dependency-helper",
    "version": "0e82305",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-helper-0e82305.jar",
          "url": "antibytes-dependency-helper-0e82305.jar",
          "size": 70569,
          "sha512": "03736b02ebcf8bbe2ada569fff6058c59e6eaa721513e75b276911574ef2df19e93b9499259d9e37b27466f7dee58d561c4e1812d0a99bc17ee70e4768d62f06",
          "sha256": "155918532444ab949966c4437071e2a208a87faa1e6100e43423a0bec4d545d1",
          "sha1": "ff28e3912db6b1405140eae29491a35c75b9dc59",
          "md5": "7b4f7c8628b73f7d437b408b0a86a5a9"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.squareup.tools.build",
          "module": "maven-archeologist",
          "version": {
            "requires": "0.0.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "0e82305"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-helper-0e82305.jar",
          "url": "antibytes-dependency-helper-0e82305.jar",
          "size": 70569,
          "sha512": "03736b02ebcf8bbe2ada569fff6058c59e6eaa721513e75b276911574ef2df19e93b9499259d9e37b27466f7dee58d561c4e1812d0a99bc17ee70e4768d62f06",
          "sha256": "155918532444ab949966c4437071e2a208a87faa1e6100e43423a0bec4d545d1",
          "sha1": "ff28e3912db6b1405140eae29491a35c75b9dc59",
          "md5": "7b4f7c8628b73f7d437b408b0a86a5a9"
        }
      ]
    }
  ]
}
