{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.grammar",
    "module": "antibytes-grammar-tools",
    "version": "0e82305",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-grammar-tools-0e82305.jar",
          "url": "antibytes-grammar-tools-0e82305.jar",
          "size": 39371,
          "sha512": "5d0a741def93632ad5112ab994e561fb0dfa61d905d232a2896d842d6e8f632cdfc3afa2a099ae26e4dfd48ab65abea7f6e26e29aa9713e21aa6442c3653f201",
          "sha256": "c8a2bb1b5cf1136dbd232cd3e8e0e3af244e4aaefe503201b9392123fa1311f8",
          "sha1": "f51a3e2ccd16f6666f771ec1f3d981774ea04b7a",
          "md5": "c2358d51e3725f9b34be093253c86fda"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "de.jflex",
          "module": "jflex",
          "version": {
            "requires": "1.8.2"
          }
        },
        {
          "group": "com.lordcodes.turtle",
          "module": "turtle",
          "version": {
            "requires": "0.7.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-grammar-tools-0e82305.jar",
          "url": "antibytes-grammar-tools-0e82305.jar",
          "size": 39371,
          "sha512": "5d0a741def93632ad5112ab994e561fb0dfa61d905d232a2896d842d6e8f632cdfc3afa2a099ae26e4dfd48ab65abea7f6e26e29aa9713e21aa6442c3653f201",
          "sha256": "c8a2bb1b5cf1136dbd232cd3e8e0e3af244e4aaefe503201b9392123fa1311f8",
          "sha1": "f51a3e2ccd16f6666f771ec1f3d981774ea04b7a",
          "md5": "c2358d51e3725f9b34be093253c86fda"
        }
      ]
    }
  ]
}
