{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.quality",
    "module": "antibytes-quality",
    "version": "0e82305",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-quality-0e82305.jar",
          "url": "antibytes-quality-0e82305.jar",
          "size": 62609,
          "sha512": "70bd0208514f97e01e4402eb595da7b95be49ad88c52e290ff694452b62b58a11d486ee13f9f21ccb6ea924b5acfab91cd3856095ffd1497d70b0b26624ca864",
          "sha256": "75b133ca859c72d9a76a6ab4ad8a8e9a1e71223d0922713e9ee5f7746c92779b",
          "sha1": "7d07d6e77051a949252c8d0c30157c3db441bc29",
          "md5": "4a39e98e5f2f48bc79e16e3e111fe656"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.21.0"
          }
        },
        {
          "group": "org.sonarsource.scanner.gradle",
          "module": "sonarqube-gradle-plugin",
          "version": {
            "requires": "3.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "binary-compatibility-validator",
          "version": {
            "requires": "0.12.1"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "0e82305"
          }
        },
        {
          "group": "tech.antibytes.gradle.dependency.helper",
          "module": "antibytes-dependency-helper",
          "version": {
            "requires": "0e82305"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-quality-0e82305.jar",
          "url": "antibytes-quality-0e82305.jar",
          "size": 62609,
          "sha512": "70bd0208514f97e01e4402eb595da7b95be49ad88c52e290ff694452b62b58a11d486ee13f9f21ccb6ea924b5acfab91cd3856095ffd1497d70b0b26624ca864",
          "sha256": "75b133ca859c72d9a76a6ab4ad8a8e9a1e71223d0922713e9ee5f7746c92779b",
          "sha1": "7d07d6e77051a949252c8d0c30157c3db441bc29",
          "md5": "4a39e98e5f2f48bc79e16e3e111fe656"
        }
      ]
    }
  ]
}
