{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/61a6ee5/test-utils-coroutine-61a6ee5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "61a6ee5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js-61a6ee5.klib",
          "url": "test-utils-coroutine-js-61a6ee5.klib",
          "size": 10181,
          "sha512": "4d538dda556640ad924067768c06e01298bec4c8cb2a50337bb859626ac043374da1fbeffd4c75bbd6ca8c6639fb094990872fcf287b66abc96eb9ad9339a978",
          "sha256": "46aa6af22e39c3324ff9a8ca7903c72c8dbb1a324859a47cac347445edf5da32",
          "sha1": "2d905f894e9abc3dbace42a093758d5acd1eb15a",
          "md5": "0101193d538537e530622c63cc9596f2"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js-61a6ee5.klib",
          "url": "test-utils-coroutine-js-61a6ee5.klib",
          "size": 10181,
          "sha512": "4d538dda556640ad924067768c06e01298bec4c8cb2a50337bb859626ac043374da1fbeffd4c75bbd6ca8c6639fb094990872fcf287b66abc96eb9ad9339a978",
          "sha256": "46aa6af22e39c3324ff9a8ca7903c72c8dbb1a324859a47cac347445edf5da32",
          "sha1": "2d905f894e9abc3dbace42a093758d5acd1eb15a",
          "md5": "0101193d538537e530622c63cc9596f2"
        }
      ]
    }
  ]
}
