{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/9401af5/test-utils-coroutine-9401af5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "9401af5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-coroutine-jvm-9401af5.jar",
          "url": "test-utils-coroutine-jvm-9401af5.jar",
          "size": 11975,
          "sha512": "c235cacadea63beff5834765a3ae857c270aa20bb3a36cf29e3e9e26f693b70bcef4a86da3b0b9320b2b48406cf5f5832cfdc331d74a9e5af3b82055dea2951f",
          "sha256": "e961e526447c6ed71dd2ce19683e6b19c2f7afdae958f932ad5022a08c659796",
          "sha1": "2ace93a97e1aae2bb95fd4790c8fabf32871e73f",
          "md5": "3025822c2f6646a1e5c575efded495a7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-jvm-9401af5.jar",
          "url": "test-utils-coroutine-jvm-9401af5.jar",
          "size": 11975,
          "sha512": "c235cacadea63beff5834765a3ae857c270aa20bb3a36cf29e3e9e26f693b70bcef4a86da3b0b9320b2b48406cf5f5832cfdc331d74a9e5af3b82055dea2951f",
          "sha256": "e961e526447c6ed71dd2ce19683e6b19c2f7afdae958f932ad5022a08c659796",
          "sha1": "2ace93a97e1aae2bb95fd4790c8fabf32871e73f",
          "md5": "3025822c2f6646a1e5c575efded495a7"
        }
      ]
    }
  ]
}
