{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/9401af5/test-utils-coroutine-9401af5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "9401af5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine.klib",
          "url": "test-utils-coroutine-iossimulatorarm64-9401af5.klib",
          "size": 10210,
          "sha512": "4e6c8650d52b4ac184d14f704e3a2a119b82315ba8665094297dde817c1c6577a274a1a2e6359a9d6462dfe15d26359db6fd028bf3cc6e44b27ffe56eb1be57b",
          "sha256": "73ed4ced9dd0d433a6e8a1e48b1406ae0a38155c2f9061ee8cf21f5e9dc30343",
          "sha1": "1f2884ffc19bcb91d904ed12d8b018dd5e120388",
          "md5": "fa44c515a7a2019b52cf5c51c692b7f2"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-iossimulatorarm64-9401af5-metadata.jar",
          "url": "test-utils-coroutine-iossimulatorarm64-9401af5-metadata.jar",
          "size": 261,
          "sha512": "e64922344743d3873307b052d792e916d3cc7d58f8138621c5b3fb8df3f26932d963c73814044602c52c321f1f7363fd238503c605747a3ddb98ae1f973c54b7",
          "sha256": "0eb835f07e0aea608928bc3ef0a7df7aa40d9a48cbd14e4ef18444fed35016c8",
          "sha1": "ff03ff0956645ad7b042ffc03abed9f59ab2b071",
          "md5": "4fea52442d68d4f427f828be8f89a290"
        }
      ]
    }
  ]
}
