{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.dokka",
    "module": "antibytes-dokka-configuration",
    "version": "0e82305",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dokka-configuration-0e82305.jar",
          "url": "antibytes-dokka-configuration-0e82305.jar",
          "size": 7889,
          "sha512": "89d4215b52259a92d1eba269700274e75ec7d83802a40b51c3bc2a299f38989c792d5b209bf6cd6242d000d50e4f2c097caaac4ea31dc0d3a6cddc26195ad99e",
          "sha256": "35cbbb31443de6ec7a8f2cc95dc3eaa2ff45ebc59ef614797126b90b9fe81960",
          "sha1": "9de0566fd3e4a5209b150bbe5a9bc6d39faf7bf7",
          "md5": "4c9a319c8b1a7be4645386058a322ac0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.7.20"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "0e82305"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dokka-configuration-0e82305.jar",
          "url": "antibytes-dokka-configuration-0e82305.jar",
          "size": 7889,
          "sha512": "89d4215b52259a92d1eba269700274e75ec7d83802a40b51c3bc2a299f38989c792d5b209bf6cd6242d000d50e4f2c097caaac4ea31dc0d3a6cddc26195ad99e",
          "sha256": "35cbbb31443de6ec7a8f2cc95dc3eaa2ff45ebc59ef614797126b90b9fe81960",
          "sha1": "9de0566fd3e4a5209b150bbe5a9bc6d39faf7bf7",
          "md5": "4c9a319c8b1a7be4645386058a322ac0"
        }
      ]
    }
  ]
}
