{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/61a6ee5/test-utils-resourceloader-61a6ee5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "61a6ee5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-resourceloader-jvm-61a6ee5.jar",
          "url": "test-utils-resourceloader-jvm-61a6ee5.jar",
          "size": 5533,
          "sha512": "fa228f3db1dd3bbe59bbbfebb0b1896cb5ad88f92c6c348cf6437e4fa682722c11fc0b40c02bc7991fcedf2947f91e6f7de0237068f6c3f100326ac0c2c5d17c",
          "sha256": "f3f57c8411da0f8da401f5ac6715bce0b4c610601b5bf1dddb47fc5eeb845f37",
          "sha1": "b3b33619aa7490ca6468a204f35f696937093bfd",
          "md5": "9a809369dc66e97e022383b15ad53931"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-jvm-61a6ee5.jar",
          "url": "test-utils-resourceloader-jvm-61a6ee5.jar",
          "size": 5533,
          "sha512": "fa228f3db1dd3bbe59bbbfebb0b1896cb5ad88f92c6c348cf6437e4fa682722c11fc0b40c02bc7991fcedf2947f91e6f7de0237068f6c3f100326ac0c2c5d17c",
          "sha256": "f3f57c8411da0f8da401f5ac6715bce0b4c610601b5bf1dddb47fc5eeb845f37",
          "sha1": "b3b33619aa7490ca6468a204f35f696937093bfd",
          "md5": "9a809369dc66e97e022383b15ad53931"
        }
      ]
    }
  ]
}
