{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/9401af5/test-utils-ktor-9401af5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "9401af5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-9401af5.klib",
          "url": "test-utils-ktor-js-9401af5.klib",
          "size": 12119,
          "sha512": "6bfe2981a8fed347679a829d20644d200f79f33fb224eb580db0ae0fd6b8307797651149b8942af4dc6a3fc6c4eb69e4e4fd104d4914bcaddfec4816dd9be387",
          "sha256": "deb4d246000d163760f16638448f271fb97052241444830f94bb6b52fee0f865",
          "sha1": "3930a0283ced3cdea7c1a3e370b791212e34370e",
          "md5": "6f052e8f81a88a6fe1f48d2e769e4257"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-js-9401af5.klib",
          "url": "test-utils-ktor-js-9401af5.klib",
          "size": 12119,
          "sha512": "6bfe2981a8fed347679a829d20644d200f79f33fb224eb580db0ae0fd6b8307797651149b8942af4dc6a3fc6c4eb69e4e4fd104d4914bcaddfec4816dd9be387",
          "sha256": "deb4d246000d163760f16638448f271fb97052241444830f94bb6b52fee0f865",
          "sha1": "3930a0283ced3cdea7c1a3e370b791212e34370e",
          "md5": "6f052e8f81a88a6fe1f48d2e769e4257"
        }
      ]
    }
  ]
}
