{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/9401af5/test-utils-9401af5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "9401af5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iossimulatorarm64-9401af5.klib",
          "size": 14405,
          "sha512": "a83f77382284dc34042a29118c65e364fda5f87b90e7f94435bec85fb1decc5cbdcf90700fdb923f9eaaf0b78b510c4e2829431f37750f322971fa5016bab1ab",
          "sha256": "df5c1c6e76e8d90512ebb6607b0347d4c076a929b5c9b1ebe1f919c5f52dbf82",
          "sha1": "bc592cbed3c070d337e93db635b8046bad950758",
          "md5": "764862a43813ad1f5f4681b9d1726518"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iossimulatorarm64-9401af5-metadata.jar",
          "url": "test-utils-iossimulatorarm64-9401af5-metadata.jar",
          "size": 261,
          "sha512": "29192d8506440c317e15e4cba376f3649f431fbb95541c271c64473d9b0b316cbdaf579b3f6a600726e994496ecc7089a5ae73bfda9a6cf31b3d4e330f5d6985",
          "sha256": "0232f07caa62f56feb32b4432af6d5b7f610951f6ed4c185b099fcf8d3e7254b",
          "sha1": "7e8db6f5765b2765a323d9835790eefa7b86a4eb",
          "md5": "a3d94c8ec8a4eaa939de6756ac1f9359"
        }
      ]
    }
  ]
}
