{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-dependency",
    "version": "9e2ffe9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-dependency-9e2ffe9.jar",
          "url": "antibytes-dependency-9e2ffe9.jar",
          "size": 83579,
          "sha512": "b96c0f8ddc382dd4c887efef4af2c79ba3a2939f4c8a081b58d764d56951cda95334b9a0f4bb2ed19e004fb7a0dfd415c74d1265bb4d1489e47fb20673c7fde0",
          "sha256": "9123b71e8b599e4d90c46ee216fcf283628b61136de0a5bd835afb2b645b9426",
          "sha1": "c6c5540bbb72633d66c35479612afde12c006208",
          "md5": "fc721412137c4066e732f80892622219"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu-gradle-plugin",
          "version": {
            "requires": "0.18.3"
          },
          "excludes": [
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.3.0"
          }
        },
        {
          "group": "com.github.ben-manes",
          "module": "gradle-versions-plugin",
          "version": {
            "requires": "0.42.0"
          }
        },
        {
          "group": "org.owasp",
          "module": "dependency-check-gradle",
          "version": {
            "requires": "7.2.0"
          }
        },
        {
          "group": "com.pinterest",
          "module": "ktlint",
          "version": {
            "requires": "0.47.1"
          },
          "excludes": [
            {
              "group": "ch.qos.logback",
              "module": "logback-classic"
            },
            {
              "group": "org.slf4j",
              "module": "slf4j-simple"
            }
          ]
        },
        {
          "group": "com.diffplug.spotless",
          "module": "spotless-plugin-gradle",
          "version": {
            "requires": "6.11.0"
          },
          "excludes": [
            {
              "group": "org.codehaus.groovy",
              "module": "groovy-xml"
            }
          ]
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "9e2ffe9"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-dependency-9e2ffe9.jar",
          "url": "antibytes-dependency-9e2ffe9.jar",
          "size": 83579,
          "sha512": "b96c0f8ddc382dd4c887efef4af2c79ba3a2939f4c8a081b58d764d56951cda95334b9a0f4bb2ed19e004fb7a0dfd415c74d1265bb4d1489e47fb20673c7fde0",
          "sha256": "9123b71e8b599e4d90c46ee216fcf283628b61136de0a5bd835afb2b645b9426",
          "sha1": "c6c5540bbb72633d66c35479612afde12c006208",
          "md5": "fc721412137c4066e732f80892622219"
        }
      ]
    }
  ]
}
