{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-ktor/9401af5/test-utils-ktor-9401af5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-ktor",
    "version": "9401af5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-ktor-jvm-9401af5.jar",
          "url": "test-utils-ktor-jvm-9401af5.jar",
          "size": 26352,
          "sha512": "4652edc3d954b2626863699fe9968e01060407e2b82711a51e5aaa67ceeaa64856eb48c66c5c022a47d26f274024b3e7a5a9662a0d25aeb03967b68ed911ec1e",
          "sha256": "dca9150ba8ed0054878043c5f5d494ff13b215ebac6245c86652bd9f86ea2a1f",
          "sha1": "f2257d1edd85a0ba50fd43eb758f9373355e41a4",
          "md5": "f54d1ad8a5442c042539782b597af9fa"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-java",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-mock",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "co.touchlab",
          "module": "stately-iso-collections",
          "version": {
            "requires": "1.2.3"
          },
          "excludes": [
            {
              "group": "org.jetbrains.kotlinx",
              "module": "kotlinx-coroutines-core"
            }
          ]
        }
      ],
      "files": [
        {
          "name": "test-utils-ktor-jvm-9401af5.jar",
          "url": "test-utils-ktor-jvm-9401af5.jar",
          "size": 26352,
          "sha512": "4652edc3d954b2626863699fe9968e01060407e2b82711a51e5aaa67ceeaa64856eb48c66c5c022a47d26f274024b3e7a5a9662a0d25aeb03967b68ed911ec1e",
          "sha256": "dca9150ba8ed0054878043c5f5d494ff13b215ebac6245c86652bd9f86ea2a1f",
          "sha1": "f2257d1edd85a0ba50fd43eb758f9373355e41a4",
          "md5": "f54d1ad8a5442c042539782b597af9fa"
        }
      ]
    }
  ]
}
