{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle-plugins",
    "module": "antibytes-publishing",
    "version": "9e2ffe9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "9e2ffe9"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-9e2ffe9.jar",
          "url": "antibytes-publishing-9e2ffe9.jar",
          "size": 117663,
          "sha512": "2e8ddba33db8cca5a844adaae4fce63f2634d28437eee94c9fec615feab1adbcb4c3ca661cc9d34e57b40b1fb479a3a865393b991ee6e5e27178b1c8c6ad5738",
          "sha256": "d16c53e5f037c4e661f05762994e9400a03682bc9f4c3002c99609540338f190",
          "sha1": "9316bdf913cefab48de1ed1ac3a0e584344cc266",
          "md5": "1e10b5b03c4ecfb8c5fa6a72771239b2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.eclipse.jgit",
          "module": "org.eclipse.jgit",
          "version": {
            "requires": "6.3.0.202209071007-r"
          }
        },
        {
          "group": "com.palantir.gradle.gitversion",
          "module": "gradle-git-version",
          "version": {
            "requires": "0.15.0"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "9e2ffe9"
          }
        },
        {
          "group": "tech.antibytes.gradle-plugins",
          "module": "antibytes-versioning",
          "version": {
            "requires": "9e2ffe9"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-publishing-9e2ffe9.jar",
          "url": "antibytes-publishing-9e2ffe9.jar",
          "size": 117663,
          "sha512": "2e8ddba33db8cca5a844adaae4fce63f2634d28437eee94c9fec615feab1adbcb4c3ca661cc9d34e57b40b1fb479a3a865393b991ee6e5e27178b1c8c6ad5738",
          "sha256": "d16c53e5f037c4e661f05762994e9400a03682bc9f4c3002c99609540338f190",
          "sha1": "9316bdf913cefab48de1ed1ac3a0e584344cc266",
          "md5": "1e10b5b03c4ecfb8c5fa6a72771239b2"
        }
      ]
    }
  ]
}
