{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle.configuration.kmp",
    "module": "antibytes-kmp-configuration",
    "version": "0e82305",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-kmp-configuration-0e82305.jar",
          "url": "antibytes-kmp-configuration-0e82305.jar",
          "size": 67704,
          "sha512": "ad7152e217eb2b68c5e37f553bb2bf003272612b1c82fe107dabb260d1cda511d0830b4f467c262f360b206e7bb3a936e0b51ff049fdb01debfc61993c85ded9",
          "sha256": "18373f1d4ed6f908c374dbcc33be8396aef411d5ea56c2d6c2e563a5c5ab17da",
          "sha1": "e524895c89954d1fa83eabb7f666a5cc073dfc6e",
          "md5": "3c77211144fb0bc45f2c0bb5cd4e00a2"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "0e82305"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-kmp-configuration-0e82305.jar",
          "url": "antibytes-kmp-configuration-0e82305.jar",
          "size": 67704,
          "sha512": "ad7152e217eb2b68c5e37f553bb2bf003272612b1c82fe107dabb260d1cda511d0830b4f467c262f360b206e7bb3a936e0b51ff049fdb01debfc61993c85ded9",
          "sha256": "18373f1d4ed6f908c374dbcc33be8396aef411d5ea56c2d6c2e563a5c5ab17da",
          "sha1": "e524895c89954d1fa83eabb7f666a5cc073dfc6e",
          "md5": "3c77211144fb0bc45f2c0bb5cd4e00a2"
        }
      ]
    }
  ]
}
