{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "61a6ee5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-metadata-61a6ee5-all.jar",
          "url": "test-utils-coroutine-61a6ee5-all.jar",
          "size": 10616,
          "sha512": "31d63ec4ff95c724cfd05c4833514e0ab6adccd9f39b645be687b2531d15bef9a8261488abc83df8971d22e5e7d3b5c9c5bb4a1fb904535f49b716fc5df7e0e1",
          "sha256": "8aedfa40a1f4587a30e5842c71b2e23de0b89b7d1b5414395326796c6742b1b2",
          "sha1": "bd0d6cdebc481ad1ec14916afb17fc27294ad4a6",
          "md5": "87695d97d2cb23cfae6e9800f600452f"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-coroutine-61a6ee5.jar",
          "url": "test-utils-coroutine-61a6ee5.jar",
          "size": 3034,
          "sha512": "693d6743983cb1be454b701529f7353877593fae9a3fcc7ee3f1a124ceaa5d0392840e0c0901e87a81a3fe974c6f6471bc8aa5c4b19e029742d0da0d1940cd45",
          "sha256": "71a36aab7b8d3ca34847ae9ea8da2ba5628f11136880ccabe78a8cbcfdc8e36a",
          "sha1": "6fb5d88d66e916fcbc4ee3c1bb4d9fe736652eda",
          "md5": "203906aa5f5a9c52da75bd0460e5a417"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/61a6ee5/test-utils-coroutine-android-61a6ee5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "61a6ee5"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/61a6ee5/test-utils-coroutine-android-61a6ee5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "61a6ee5"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iosarm64/61a6ee5/test-utils-coroutine-iosarm64-61a6ee5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iosarm64",
        "version": "61a6ee5"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iosarm64/61a6ee5/test-utils-coroutine-iosarm64-61a6ee5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iosarm64",
        "version": "61a6ee5"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iossimulatorarm64/61a6ee5/test-utils-coroutine-iossimulatorarm64-61a6ee5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iossimulatorarm64",
        "version": "61a6ee5"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iossimulatorarm64/61a6ee5/test-utils-coroutine-iossimulatorarm64-61a6ee5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iossimulatorarm64",
        "version": "61a6ee5"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iosx64/61a6ee5/test-utils-coroutine-iosx64-61a6ee5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iosx64",
        "version": "61a6ee5"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iosx64/61a6ee5/test-utils-coroutine-iosx64-61a6ee5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iosx64",
        "version": "61a6ee5"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-js/61a6ee5/test-utils-coroutine-js-61a6ee5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-js",
        "version": "61a6ee5"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-js/61a6ee5/test-utils-coroutine-js-61a6ee5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-js",
        "version": "61a6ee5"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/61a6ee5/test-utils-coroutine-jvm-61a6ee5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "61a6ee5"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/61a6ee5/test-utils-coroutine-jvm-61a6ee5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "61a6ee5"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-linuxx64/61a6ee5/test-utils-coroutine-linuxx64-61a6ee5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-linuxx64",
        "version": "61a6ee5"
      }
    }
  ]
}
