{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/61a6ee5/test-utils-annotations-61a6ee5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "61a6ee5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-annotations-jvm-61a6ee5.jar",
          "url": "test-utils-annotations-jvm-61a6ee5.jar",
          "size": 10817,
          "sha512": "0ff42f29b1fe24d511213c23dcfcc1a3656deb5f0aae336ff9c3823c90590039077af73c55dad52a5c855ae47623867840b166e9c66545c341a5352b06b43554",
          "sha256": "0e45372bbd210935e05ae17c521d438161eceef9995839701a3591ad9e7685a6",
          "sha1": "4f5bc134e223c8c4e7f9959781f034bc788234d2",
          "md5": "eacc5a2b8161cae1b6cabf0cbde23000"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-jvm-61a6ee5.jar",
          "url": "test-utils-annotations-jvm-61a6ee5.jar",
          "size": 10817,
          "sha512": "0ff42f29b1fe24d511213c23dcfcc1a3656deb5f0aae336ff9c3823c90590039077af73c55dad52a5c855ae47623867840b166e9c66545c341a5352b06b43554",
          "sha256": "0e45372bbd210935e05ae17c521d438161eceef9995839701a3591ad9e7685a6",
          "sha1": "4f5bc134e223c8c4e7f9959781f034bc788234d2",
          "md5": "eacc5a2b8161cae1b6cabf0cbde23000"
        }
      ]
    }
  ]
}
