{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/9401af5/test-utils-9401af5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "9401af5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iosarm64-9401af5.klib",
          "size": 14316,
          "sha512": "c77850254b2f5394110262f86f71576eaf68e40b44bcd198a3f6c39249036c07a608297345781f2efe32f702335a2bfc440ad4976f0ef653acbcb8e1f52a2c20",
          "sha256": "c4cab3c108c8626ad2e7cf6d1ade158666a8db0735f78f7920f6312e9ff9da6d",
          "sha1": "4d1bd781f2f280911e1f1f302bf2e9cfceddf52d",
          "md5": "3500ffd51405ad1cd1cd2de0d9c2eec7"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iosarm64-9401af5-metadata.jar",
          "url": "test-utils-iosarm64-9401af5-metadata.jar",
          "size": 261,
          "sha512": "29192d8506440c317e15e4cba376f3649f431fbb95541c271c64473d9b0b316cbdaf579b3f6a600726e994496ecc7089a5ae73bfda9a6cf31b3d4e330f5d6985",
          "sha256": "0232f07caa62f56feb32b4432af6d5b7f610951f6ed4c185b099fcf8d3e7254b",
          "sha1": "7e8db6f5765b2765a323d9835790eefa7b86a4eb",
          "md5": "a3d94c8ec8a4eaa939de6756ac1f9359"
        }
      ]
    }
  ]
}
