{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-coroutine/9401af5/test-utils-coroutine-9401af5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "9401af5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js-9401af5.klib",
          "url": "test-utils-coroutine-js-9401af5.klib",
          "size": 10181,
          "sha512": "e4ada3bdae90f0350bc9c5d082c3040254a565b30d2619e506285ce9ebc7f7812606f225bed19bdc11679b37f8923589494f33bea9da949ffdaf3188231d7595",
          "sha256": "cab7d5226b57ebfa4cb2b63adfea6bc2569aa1c08f3f93d06b541d6619d0c704",
          "sha1": "0f68f7712ed87be5131b6928eed8b1457cef2bfc",
          "md5": "5c714106c8d158854dd0c3e0a9698209"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core-js",
          "version": {
            "requires": "1.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-js-9401af5.klib",
          "url": "test-utils-coroutine-js-9401af5.klib",
          "size": 10181,
          "sha512": "e4ada3bdae90f0350bc9c5d082c3040254a565b30d2619e506285ce9ebc7f7812606f225bed19bdc11679b37f8923589494f33bea9da949ffdaf3188231d7595",
          "sha256": "cab7d5226b57ebfa4cb2b63adfea6bc2569aa1c08f3f93d06b541d6619d0c704",
          "sha1": "0f68f7712ed87be5131b6928eed8b1457cef2bfc",
          "md5": "5c714106c8d158854dd0c3e0a9698209"
        }
      ]
    }
  ]
}
