{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-coroutine",
    "version": "9401af5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.6.4"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-coroutine-metadata-9401af5-all.jar",
          "url": "test-utils-coroutine-9401af5-all.jar",
          "size": 10616,
          "sha512": "ef6234aef2b60e2b8eb1354ee3c15fb5ef11df71647b7ec808506598eca28787bf0231c1b90c861f404eff8c1eb1d141d0bc8f72363d98add2699302c1aca03a",
          "sha256": "541ccc2e6749c40d63874223bb5cbbdd3158faf0cd4479b16c35e47719150ab1",
          "sha1": "e39bcf73b5061a214f56b34255b57e8d52ff44bb",
          "md5": "c04bc31e01d7157c0fcdeab675e6d5d0"
        }
      ]
    },
    {
      "name": "commonMainMetadataElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "test-utils-coroutine-9401af5.jar",
          "url": "test-utils-coroutine-9401af5.jar",
          "size": 3034,
          "sha512": "3a40068025e57b30329c9e59e2b544c6c1d937558bb4b81300f576dc2e6ad6c583d4cd7e48228459534317d2f887b807e0f30a1dce457d935901dcc7ab616a03",
          "sha256": "f6a08c3ff85d52d7aa6673358f0b2aaa198fea7c9578ea80c2ca53433fac20a7",
          "sha1": "f270a21f15062768bd97fd8187abe9ab70d7361b",
          "md5": "3c69816614e344c4297934f09d5246f6"
        }
      ]
    },
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/9401af5/test-utils-coroutine-android-9401af5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "9401af5"
      }
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-android/9401af5/test-utils-coroutine-android-9401af5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-android",
        "version": "9401af5"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iosarm64/9401af5/test-utils-coroutine-iosarm64-9401af5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iosarm64",
        "version": "9401af5"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iosarm64/9401af5/test-utils-coroutine-iosarm64-9401af5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iosarm64",
        "version": "9401af5"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iossimulatorarm64/9401af5/test-utils-coroutine-iossimulatorarm64-9401af5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iossimulatorarm64",
        "version": "9401af5"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iossimulatorarm64/9401af5/test-utils-coroutine-iossimulatorarm64-9401af5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iossimulatorarm64",
        "version": "9401af5"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iosx64/9401af5/test-utils-coroutine-iosx64-9401af5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iosx64",
        "version": "9401af5"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-iosx64/9401af5/test-utils-coroutine-iosx64-9401af5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-iosx64",
        "version": "9401af5"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-js/9401af5/test-utils-coroutine-js-9401af5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-js",
        "version": "9401af5"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-js/9401af5/test-utils-coroutine-js-9401af5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-js",
        "version": "9401af5"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/9401af5/test-utils-coroutine-jvm-9401af5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "9401af5"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-jvm/9401af5/test-utils-coroutine-jvm-9401af5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-jvm",
        "version": "9401af5"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../test-utils-coroutine-linuxx64/9401af5/test-utils-coroutine-linuxx64-9401af5.module",
        "group": "tech.antibytes.test-utils-kmp",
        "module": "test-utils-coroutine-linuxx64",
        "version": "9401af5"
      }
    }
  ]
}
