{
  "formatVersion": "1.1",
  "component": {
    "group": "tech.antibytes.gradle",
    "module": "antibytes-runtime-configuration",
    "version": "0e82305",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "antibytes-runtime-configuration-0e82305.jar",
          "url": "antibytes-runtime-configuration-0e82305.jar",
          "size": 9073,
          "sha512": "5e93dac12cb743488811a92b59cf8e088563e055e8484647b9d172db41758cc977302864a7a27f8156f6e6431850ca3efe06e06eeae603ca5656273665e8a8e7",
          "sha256": "d70a341733ae31e0d1f754dd08c4629078c20c82fd4f425fd96cb35888c81e5c",
          "sha1": "93645d63bd29cbbc55d217cd2e80f6fa8868c21a",
          "md5": "36efa2b26d409ff8d26c3112bb84627d"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "tech.antibytes.gradle",
          "module": "antibytes-gradle-utils",
          "version": {
            "requires": "0e82305"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "antibytes-runtime-configuration-0e82305.jar",
          "url": "antibytes-runtime-configuration-0e82305.jar",
          "size": 9073,
          "sha512": "5e93dac12cb743488811a92b59cf8e088563e055e8484647b9d172db41758cc977302864a7a27f8156f6e6431850ca3efe06e06eeae603ca5656273665e8a8e7",
          "sha256": "d70a341733ae31e0d1f754dd08c4629078c20c82fd4f425fd96cb35888c81e5c",
          "sha1": "93645d63bd29cbbc55d217cd2e80f6fa8868c21a",
          "md5": "36efa2b26d409ff8d26c3112bb84627d"
        }
      ]
    }
  ]
}
