{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/9401af5/test-utils-annotations-9401af5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "9401af5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-9401af5.klib",
          "url": "test-utils-annotations-js-9401af5.klib",
          "size": 9733,
          "sha512": "91941ee376e1c6a7fdfe854999e4455259b3ca6f33e5769e95c9fb32c0d4ee8338c5f829a121cc8177fe0a0a0ce917fe061b7bdac504aee6a78378977f944c12",
          "sha256": "995ddef1e1512c2d9db236b9c9100d6a163fb7a9782dfbd64ac134f162b78912",
          "sha1": "cd4a9c3d4bb4f23c7e4d8229c51fd59f0e8d7feb",
          "md5": "a32c1391c30b2e27f45a5c70ed8aa55a"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-js-9401af5.klib",
          "url": "test-utils-annotations-js-9401af5.klib",
          "size": 9733,
          "sha512": "91941ee376e1c6a7fdfe854999e4455259b3ca6f33e5769e95c9fb32c0d4ee8338c5f829a121cc8177fe0a0a0ce917fe061b7bdac504aee6a78378977f944c12",
          "sha256": "995ddef1e1512c2d9db236b9c9100d6a163fb7a9782dfbd64ac134f162b78912",
          "sha1": "cd4a9c3d4bb4f23c7e4d8229c51fd59f0e8d7feb",
          "md5": "a32c1391c30b2e27f45a5c70ed8aa55a"
        }
      ]
    }
  ]
}
