{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/9401af5/test-utils-annotations-9401af5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "9401af5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "test-utils-annotations-jvm-9401af5.jar",
          "url": "test-utils-annotations-jvm-9401af5.jar",
          "size": 10817,
          "sha512": "7c2b3492607eb3df0b614b959ab534afa6f3a8ee7564dbcd6c11f3e6720b9916934d065e36e2d9b7bdf097dfd9882abc6e81c4b57395fe9b83e9dcb622120e5c",
          "sha256": "f83f562a384ba4678c1dccb9127db4f0ceb4e4832d0d9e0664cbbb54c44d530a",
          "sha1": "7957af71c5c3d68f5c5c13fd634594db880656ea",
          "md5": "02e2aee1474584b5df5432b7010d135b"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-junit",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-jvm-9401af5.jar",
          "url": "test-utils-annotations-jvm-9401af5.jar",
          "size": 10817,
          "sha512": "7c2b3492607eb3df0b614b959ab534afa6f3a8ee7564dbcd6c11f3e6720b9916934d065e36e2d9b7bdf097dfd9882abc6e81c4b57395fe9b83e9dcb622120e5c",
          "sha256": "f83f562a384ba4678c1dccb9127db4f0ceb4e4832d0d9e0664cbbb54c44d530a",
          "sha1": "7957af71c5c3d68f5c5c13fd634594db880656ea",
          "md5": "02e2aee1474584b5df5432b7010d135b"
        }
      ]
    }
  ]
}
