{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/9401af5/test-utils-9401af5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "9401af5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-9401af5.klib",
          "url": "test-utils-js-9401af5.klib",
          "size": 12070,
          "sha512": "913d66b451bc9d93a641b0a9a4ebe73417fd1db47d0b5966049468c9db68a1770f94789d9b5c2430dc47d13648ddd4760c0d97818ae191800002452cc90f9a0c",
          "sha256": "706725a32690592f3f7e358ff1e146f683cf3cff33b83615c67370f26cbf892a",
          "sha1": "2582306c9588729b8bab281d0389eb9ac2487929",
          "md5": "1704494d0e0d647cc76d7c54804ac691"
        }
      ]
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-nodejs",
          "version": {
            "requires": "0.0.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-js",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-js-9401af5.klib",
          "url": "test-utils-js-9401af5.klib",
          "size": 12070,
          "sha512": "913d66b451bc9d93a641b0a9a4ebe73417fd1db47d0b5966049468c9db68a1770f94789d9b5c2430dc47d13648ddd4760c0d97818ae191800002452cc90f9a0c",
          "sha256": "706725a32690592f3f7e358ff1e146f683cf3cff33b83615c67370f26cbf892a",
          "sha1": "2582306c9588729b8bab281d0389eb9ac2487929",
          "md5": "1704494d0e0d647cc76d7c54804ac691"
        }
      ]
    }
  ]
}
