{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-annotations/61a6ee5/test-utils-annotations-61a6ee5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-annotations",
    "version": "61a6ee5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations.klib",
          "url": "test-utils-annotations-iosx64-61a6ee5.klib",
          "size": 11314,
          "sha512": "ea144cab8ebc3e6a232c1c1081208ff4aea2db5fb442d6bcb6d9b3754e39ba2d43a6abcfa27066b763d682828b688b5f6a4da905fd95ea95dbb680a6467a5f0c",
          "sha256": "a289607ed549dfd78adee106fddbbfd91c226006272d36a194568739015aa316",
          "sha1": "0dc10284a8525b4a96e0bebf51e8748e56529d12",
          "md5": "d84f1f9aebf41f389e54a73509ad0606"
        }
      ]
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-annotations-iosx64-61a6ee5-metadata.jar",
          "url": "test-utils-annotations-iosx64-61a6ee5-metadata.jar",
          "size": 261,
          "sha512": "5e0fb4f02d1748320860cb4023a4acc3bd8efd7c0445fa2db1666638c68fcc0e85d5c127ee05530049bae9e75579088ed12174093b9868fee9ae70ef772b98f5",
          "sha256": "234fb905bfe8faf67b0c6e9d52a13dd7d49414992a62ce7263bbe54fcf0b3465",
          "sha1": "582c3bb353bc7d6f9a8d30a5e8bcc9a8456cbc50",
          "md5": "7ea944254c125f087837b2cf12a84b8f"
        }
      ]
    }
  ]
}
