{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils-resourceloader/61a6ee5/test-utils-resourceloader-61a6ee5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils-resourceloader",
    "version": "61a6ee5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader.klib",
          "url": "test-utils-resourceloader-iossimulatorarm64-61a6ee5.klib",
          "size": 12951,
          "sha512": "ef348779e4f1a42ca14d1dd5d6094f4b858a6ef6384c064af86a44b80f149a4a46f326676f3f5393fd964d4ec2669d7f49fdfa989bc2db6cd7a034b165ab10d3",
          "sha256": "31e73ccaffabdf9994f5dc643372a6f48ac9f9a19901d96122bdcf6c17c5f997",
          "sha1": "2999a2a2e1f8572af551acb6600ae6a6aa5eed48",
          "md5": "66321d6a894f9bdf98de4e775614d366"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-resourceloader-iossimulatorarm64-61a6ee5-metadata.jar",
          "url": "test-utils-resourceloader-iossimulatorarm64-61a6ee5-metadata.jar",
          "size": 261,
          "sha512": "f4c5d282a3bbc5236d6ed498ac85fd9f98946f7b317cda4ca696d4cb592b71d825f0730e4de0d34194f6e5db510761186bff9165e9d25ef1bc27ecaedd698290",
          "sha256": "818f2e887d9d0cd5b15533a518a712d323789c892855d183690c7e9a2362b004",
          "sha1": "a9001d375f0abd93bb3735202d7c8028b12335d6",
          "md5": "fefecf7103695e2c4c99c311becdb49d"
        }
      ]
    }
  ]
}
