{
  "formatVersion": "1.1",
  "component": {
    "url": "../../test-utils/61a6ee5/test-utils-61a6ee5.module",
    "group": "tech.antibytes.test-utils-kmp",
    "module": "test-utils",
    "version": "61a6ee5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils.klib",
          "url": "test-utils-iossimulatorarm64-61a6ee5.klib",
          "size": 8049,
          "sha512": "a97e564c226edcef03e1f037c84cc889a44883076915a6d06440e98b39cf82fd3673745f74af45289f477ccc844408cc314b78c9ea046f5bd61c957b7b3a0b7b",
          "sha256": "a25214cfa5e9c902b3e2d7590d41710231523eb89d1b79e79dfcfdabe45d4815",
          "sha1": "ae8b828fa96ca13c48bead86ed8621ffe4b33235",
          "md5": "65d5deb91cb28d15b3089034e100789a"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-common",
          "version": {
            "requires": "1.7.10"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test-annotations-common",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "test-utils-iossimulatorarm64-61a6ee5-metadata.jar",
          "url": "test-utils-iossimulatorarm64-61a6ee5-metadata.jar",
          "size": 261,
          "sha512": "e7f647c378d3377827b2e99e1849d2b16628eb402b08fd4922450a94867152a12c1209e9ea46cab4f1876c8625d97460407905d55add6742872106e44dca6bdc",
          "sha256": "d691f43eb9fa2aec965ac736c5e2136a4750f0836a09841721ff50a01cf32be8",
          "sha1": "3163906fb2254cbe87230435672ec844eda7bc88",
          "md5": "966ddc3e63bc1e5f557d3e6dc1952a90"
        }
      ]
    }
  ]
}
